### PR TITLE
Relax revocation to allow anyone to revoke from their wallets

### PR DESCRIPTION
**Pull request by wanderingbort**
At the request of @CraigSellars who was relaying customer requests.  Requests received requesters!

Code is in testing (thanks @faizkhan00 )

### CODE REVIEW

**Comment by marvgmail** [comment]
Is this ready to be merged?

**Comment by dexX7** [comment]
I don't like it, but the current behavior Of Omni Core is that tokens of managed properties can be revoked by any holder, so this PR reflects actual behavior.

However, I should note that even though a revoke from a non-issuer is valid, it's currently blocked on the RPC layer.

**Comment by zathras-crypto** [comment]
> However, I should note that even though a revoke from a non-issuer is valid, it's currently blocked on the RPC layer.

Indeed - didn't @CraigSellars have a usecase that required allowing non-issuers to revoke their own tokens?  (which I'm ambivalent on btw, I see no objection to allowing a user to destroy their own tokens - after all they own them so can do whatever they like with them - can you recall why we blocked this on RPC layer?  And when adding support to the UI for grants/revokes do you think we should restrict it there too?).

**Comment by dexX7** [comment]
> can you recall why we blocked this on RPC layer?

Yes. It wasn't covered by the spec (and still isn't), and there was no clear indication, it's desired or not.

But it's really [just one line that may be removed](https://github.com/OmniLayer/omnicore/blob/f1fa0164de41b739678d50104cede86f3e21647d/src/omnicore/rpctx.cpp#L667).

**Comment by dexX7** [comment]
I reviewed the pull request and the current behavior of Omni Core and it is indeed possible, on the consensus level, for anyone with a positive balance to revoke managed tokens.

While we block it on the RPC layer, it's still a consensus rule, so this pull request should be merged.

**Pull request merged**
